<?php

namespace Genius257\OpenAPI_Generator\Swagger;

/**
 * Defines a security scheme that can be used by the operations. Supported schemes are HTTP authentication, an API key (either as a header, a cookie parameter or as a query parameter), OAuth2's common flows (implicit, password, application and access code) as defined in RFC6749, and OpenID Connect Discovery.
 *
 * This object MAY be extended with Specification Extensions.
 *
 * @see https://tools.ietf.org/html/rfc6749 RFC6749
 * @see https://tools.ietf.org/html/draft-ietf-oauth-discovery-06 OpenID Connect Discovery
 * @see https://swagger.io/specification/#specificationExtensions Specification Extensions
 */
class SecurityScheme
{
    /**
     * REQUIRED. The type of the security scheme. Valid values are "apiKey", "http", "oauth2", "openIdConnect".
     *
     * @required
     *
     * @var string
     */
    public $type;

    /**
     * A short description for security scheme. CommonMark syntax MAY be used for rich text representation.
     *
     * @var string
     */
    public $description;

    /**
     * REQUIRED. The name of the header, query or cookie parameter to be used.
     *
     * @var string Applies To: apiKey
     */
    public $name;

    /**
     * REQUIRED. The location of the API key. Valid values are "query", "header" or "cookie".
     *
     * @var string Applies To: apiKey
     */
    public $in;

    /**
     * REQUIRED. The name of the HTTP Authorization scheme to be used in the Authorization header as defined in RFC7235.
     *
     * @see https://tools.ietf.org/html/rfc7235#section-5.1 Authorization header as defined in RFC7235
     *
     * @var string Applies To: http
     */
    public $scheme;

    /**
     * A hint to the client to identify how the bearer token is formatted. Bearer tokens are usually generated by an authorization server, so this information is primarily for documentation purposes.
     *
     * @var string Applies To: http ("bearer")
     */
    public $bearerFormat;

    /**
     * REQUIRED. An object containing configuration information for the flow types supported.
     *
     * @var OAuthFlows Applies To: oauth2
     */
    public $flows;

    /**
     * REQUIRED. OpenId Connect URL to discover OAuth2 configuration values. This MUST be in the form of a URL.
     *
     * @var string Applies To: openIdConnect
     */
    public $openIdConnectUrl;
}
